# Generated by Django 5.0.2 on 2024-02-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('cpf', models.CharField(max_length=11)),
                ('coren_number', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=180)),
                ('cel', models.CharField(max_length=11)),
                ('workplace', models.CharField(max_length=180)),
                ('city', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='requests/')),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
