# Generated by Django 5.0.1 on 2024-03-12 15:48

import solicitacao.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='cel',
            field=models.CharField(max_length=11, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Município'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='coren_number',
            field=models.CharField(max_length=11, verbose_name='Número de Inscrição'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='file',
            field=models.FileField(upload_to=solicitacao.models.file_path, verbose_name='Escolha o arquivo'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='name',
            field=models.CharField(max_length=180, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='workplace',
            field=models.CharField(max_length=180, verbose_name='Local de Trabalho'),
        ),
    ]
